command: [
  "uv",
  "run",
  "streamlit", 
  "run",
  "./streamlit-data-app/app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
